# Makefile for Geospatial Image Processing Library Utilities
#
# This library incorporates GDAL, for geospatial IO and reprojection, and CImg, an image processing library
#
# Author: Matt Hanson

#TARGETS = gip_test gip_testoptions gip_testchunking gip_info gip_ricedetect
#TARGETS = gip_test gip_classchange gip_ricedetect
#TARGETS = gip_volref
TARGETS = gip_funcTN gip_funcGreen

CXXFLAGS= -I/usr/include/gdal/ -I../gip/ -O2
LDFLAGS	= -L ../gip/Release -L/usr/local/lib -L/usr/local/boost/lib -L../gip/
LIBS = -lgip -lgdal -lboost_program_options -lboost_filesystem -lboost_system

#gip_blur: gip_blur.o
#	$(CC) $(LDFLAGS) $(LIBS) $@.o -o $@

all: $(TARGETS)
	make clean
	make $(TARGETS)

$(TARGETS) :
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(@).cpp -o $@ $(LIBS)

install:
	cp $(TARGETS) /usr/local/bin/

uninstall:
	for file in $(TARGETS);  do $(RM) /usr/local/bin/$$file; done

clean:
	$(RM) -rf $(TARGETS) $(LIB) *.o
